---
- name: Installing a ldap server
  hosts:  hosts
  remote_user:  theseus
  become: yes
  no_log: True
  roles:
    - openldap 
    - ldapAccountManager
  tasks:
    - name: Roles message 
      debug:
        msg: "All roles are completed"

- name: Saving annuary informations
  hosts: localhost
  gather_facts: no
  vars_files:
    - group_vars/hosts/variables.yml 
  tasks:
  - name: Backup module launched
    ldap_backup_module: 
      ldap_main_host: "{{ldap_main_host}}"
      connexion_username: "{{admin_dn}}"
      connexion_password: "{{admin_password}}"
    register: result
    no_log: True
  - debug: 
      var: result
      verbosity: 2

- name: Restoring annuary informations
  hosts: localhost
  gather_facts: no
  vars_files:
    - group_vars/hosts/variables.yml 
  tasks:
  - name: Restoration module launched
    ldap_restore_module: 
      ldap_backup_host: "{{item}}"
      connexion_username: "{{admin_dn}}"
      connexion_password: "{{admin_password}}"
      choosen_action: 'push'
    register: result
    no_log: True
    with_items: "{{ groups['hosts'] }}"    
  - debug:
      var: result
      verbosity: 2

- name: Final message
  hosts: hosts
  tasks:
    - name: Final message
      debug:
        msg: "All Playbook tasks are completed"

...