---
- name: Restauration of a ldap annuary
  hosts:  srv-ldap-05
  remote_user:  theseus
  become: yes

  # vars:
  #   var1: "Playbook variable"
  roles:
    - openldap 
    - restoreAnnuary
    - ldapAccountManager

  tasks:
  # - name: Variable precedence test
  #   debug:
  #     msg: "This is a message with the variable {{domain_name}}"

  - name: Final message 
    debug:
      msg: "All Playbook tasks are completed"
...