---
#var1: "group variable"
ansible_python_interpreter: /usr/bin/python3
admin_login: "admin"
admin_password: "theseus"
organization: "sodbaveka"
top_level_domain: "com"
domain_name: "{{organization + '.' + top_level_domain}}"
top_dn: "{{'dc=' + organization + ',dc=' + top_level_domain}}"
admin_dn: "{{'cn=' + admin_login + ',' + top_dn}}"
db_format: "MDB"
path_to_ldif_file: "/tmp/annuary_backup.ldif"
...